version: "3"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.7
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - influxdb
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.0
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
  telegraf:
    container_name: telegraf
    image: telegraf:1.15.3
    ports:
      - "57000:57000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc
      - ${PWD}/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf

volumes:
  influxdb-storage:
  grafana-storage:
